name: 功能请求
description: 提出改进MuirNGMI的想法
title: "[功能请求] "

body:
- type: markdown
  attributes:
    value: |
      这仅用于请求新的功能
- type: textarea
  id: feature-request
  attributes:
    label: 功能描述
    description: 告诉我们你想要什么功能，为什么要在MuirNGMI中添加它
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: 描述你考虑过的备选方案
- type: checkboxes
  id: area
  attributes:
    label: 受影响区域
    options:
    - label: "文档"
    - label: "安装"
    - label: "性能和可扩展性"
    - label: "安全性"
    - label: "用户体验"
    - label: "测试和发布"
    - label: "二次开发"
    - label: "其他"
